# Generated by Django 2.1.7 on 2019-06-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='story',
        ),
        migrations.AddField(
            model_name='story',
            name='images',
            field=models.ManyToManyField(to='community.Image'),
        ),
    ]
