# Generated by Django 2.1.7 on 2019-06-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20190604_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='images',
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
