# Generated by Django 2.1.7 on 2019-06-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_story_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
